import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  '2ship2harkinianSidebar': [
    {
      type: 'html',
      className: 'text--bold text--center',
      value: '2 Ship 2 Harkinian',
    },
    { type: 'autogenerated', dirName: '2ship2harkinian' }, 
    {
      type: 'link',
      label: 'Github',
      href: 'https://github.com/garrettjoecox/the-harbour',
    },
    {
      type: 'link',
      label: 'Discord',
      href: 'https://discord.gg/your-discord-server',
    },
    {
      type: 'link',
      label: 'Mod Library',
      href: 'https://github.com/garrettjoecox/the-harbour',
    },
  ],
};

export default sidebars;
